# This allows for multiple machines to join a cluster
etcd:
  advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
  discovery:                   "https://discovery.etcd.io/67d1121204a7015d25a07f1b059aac3d"

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}

# This starts the very simple Docker container
systemd:
  units:
    # Ensure docker starts automatically instead of being socket-activated
    - name: docker.socket
      enabled: false
    - name: docker.service
      enabled: true

    # Docker container started as a systemd service
    - name: helloworld.service
      enabled: true
      contents: |
        [Unit]
        Description=Hello World
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill helloworld
        ExecStartPre=-/usr/bin/docker rm helloworld
        ExecStartPre=/usr/bin/docker pull ${imagename}
        ExecStart=/usr/bin/docker run --name helloworld -p 80:80 ${imagename}

        [Install]
        WantedBy=multi-user.target